### PR TITLE
Order people by last name

### PR DESCRIPTION
**Pull request by imacrayon**

### CODE REVIEW

**Comment by kentonh** [comment]
So, we had this index sorting by last name, but it seemed strange. We changed to ID because that would show people in the order they signed up for the site.

Any other better reason we should sort them by name?

**Comment by imacrayon** [comment]
When I see a large directory of people I usually assume it will be ordered by last name. I think it would be safe to assume most people expect that? I realize users will mostly search for someone using the tags but when you first hit the page its a little unsettling to see so much anarchy lol

**Comment by kevinfalting** [comment]
Is this PR going to be accepted?

**Comment by kentonh** [comment]
Going to use a "completeness method" for ordering People index

**Pull request closed without merging**
