### PR TITLE
Add @mentions to News

### PR DESCRIPTION
**Pull request by dreamingblackcat**
Hi. This is my attempt at adding @ mentions to news ( #49 ) .  This is by no means a complete PR. I just want to let you know the approach I am taking to solve this problem and see if it is good.

My approach is by adding a many-to-many association between news and person models.
Each news' content is checked for @ mentions on save/update. For each mention extracted, a relation will be added to the person and news.

Currently @mentions for non-existent people are ignored.

On the view side, a helper method to convert a news normal content into a content with links to each person mentioned.

Showing related news on a person profile hasn't been implemented yet.

Please review it and give me feedback.

### CODE REVIEW

**Comment by kentonh** [comment]
Hey, @dreamingblackcat, this looks like a fine approach.

**Comment by dreamingblackcat** [comment]
@kentonh  Thanks for the feedback. Then I will implement the same approach for events as well.
Regarding on the profile page, suppose a profile has been mentioned in  a news/event. Do you want  those news/events on that profile page as well?

**Comment by kentonh** [comment]
Yeah, I think that'd be great.

## 

Kenton Hansen
316-833-1036
@kentonh

**Comment by sethetter** [comment]
@dreamingblackcat this looks great! Were you going to do the rest of the work in this PR or another?

**Comment by dreamingblackcat** [comment]
@sethetter  Yes, I am onto it. I guess in the same PR.

**Comment by dreamingblackcat** [comment]
HI @sethetter , @kentonh  I've refactored it a bit and added person mentions feature to events as well. 

I have a few thoughts about putting news/events on a profile page. Suppose a person is popular and got mentioned in quite a lot of news/events, there would be tons of news/events entry in his profile page. How should I handle that , via paginated entries or entire subpage under a person? 

Any thoughts? Probably we should handle that in a different PR.

**Comment by kentonh** [comment]
I think showing the 10 most recent mentions by default, with an option to
see all mentions on another view

## 

Kenton Hansen
316-833-1036
@kentonh

**Comment by dreamingblackcat** [comment]
@kentonh  I've added related news/events entry to person profile pages. At most 10 entries will be shown. If there were more, a 'View More' link which points to filtered index page of respective news/events (news only related to the person).

With this, I think this PR is good to go.

Please test this out and merge.

**Pull request merged**
